name: AutoSmelt
author: tweedjt
version: 1.0
api-version: 1.13
main: me.tweedjt.autosmelt.AutoSmelt
commands:
  AutoSmelt:
    description: Toggles Smelting
    usage: /<command>
    aliases: [as, autosmelt]
  Smelt:
    description: Spawns SmeltPick
    usage: /<command>
    aliases: [smelt]
  ASReload:
    description: Reloads Config
    usage: /<command>
    aliases: [asreload]